# Site
repository: xgro/xgro.github.io
favicon: images/xgro.ico

# Content configuration version
version: 2

# Personal info
name: 이재찬
title: DevOps 엔지니어
email: dlwocks13@gmail.com
website: https://velog.io/@xgro
website_title: Blog

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: xgro
linkedin_username: xgro

# 프로필 작성
# About Section
# about_title: About Me
about_profile_image: images/profile1.jpg
about_content: | # this will include new lines to allow paragraphs
  개발자로 일을 하면서 지속적으로 문제에 직면하게 된다는 점, 이를 해결하는 과정에서 새로운 것을 축적해 나갈 수 있다는 점이 매력적인 요소였습니다. 풀리지 않는 문제를 스스로 해결했을때의 성취감은 지속적으로 공부를 할 수 있게 만드는 원동력이 되었습니다.
  
  IoT 업무를 진행하며 클라우드에 대해서 처음 접하게 되었고, 클라우드 산업으로 커리어를 확장하기 위해 준비하였습니다. 코드스테이츠 데브옵스 부트캠프 과정을 통해 코드로 인프라를 자동화하고 개발 문화를 선도해나가는 DevOps 직무에 매료되어 직무전환을 준비하고 있습니다.
  
  ---

  ## **저는 이런 사람입니다.**
  - 책임감이 강하고 목표를 달성하기 위해 [<U>노력합니다.</U>](images/project04.jpeg)
  - 불편한 것을 당연히 여기지 않으며 이를 개선하기 위한 방안을 [<U>찾습니다.</U>](https://velog.io/@xgro/%ED%99%98%EA%B2%BD%EB%B3%80%EC%88%98-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0-%EA%B7%80%EC%B0%AE%EC%95%84)
  - 성장 과정에서 배운것을 구성원들과 공유하고 피드백을 받으며 일하는것을 [<U>좋아합니다.</U>](https://xgro.notion.site/reputation-41c97f2bf15b4fcb9d3718f356c8dd71)

  ---

  ## **저의 목표는 다음과 같습니다.**
  - 동료 개발자들이 마음놓고 실수 할 수 있는 개발환경을 구축하고 싶습니다.
  - [<U>FinOps에 관심이 많습니다.</U>](https://velog.io/@xgro/VPC-Endpoint) 담당하는 인프라에 대한 이해를 바탕으로 비용 최적화를 구현하는 엔지니어가 되고자 합니다.
  - 실수를 줄이기 위해 코드로서 인프라를 관리하는 [<U>IaC에 관심이 많습니다.</U>](https://velog.io/@xgro/terraform-infra-provisioning)

# 콘텐츠 작성
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AWS Cloud Migration 
        sub_title: On-premise to AWS Cloud
        link: https://xgro.notion.site/AWS-Cloud-Migration-2e4369d70b3d49efb8d75c8900c62f8e
        # link_text: Project Website
        additional_links:
          - title: xgro/Cloud_Migration
            icon: fab fa-github
            url: github.com/xgro/Cloud_Migration
        quote: >
          클라이언트 요구사항에 따라 온프레미스 환경에서 설치 및 운영되고 있는 사내 정보 시스템을 AWS 클라우드로 이관
        description: | # this will include new lines to allow paragraphs
          - <mark>VPC 엔드포인트</mark> 이용하여 서비스 구축 NAT gateway 대비 300GB 기준 30% 비용 절감
          - JWT 토큰 기반 인증 시스템 API Gateway <mark>권한부여자 구현</mark>함으로서 인증 서버 속도 개선
          - Private 환경으로 인스턴스 구성
          - Cloudmap 사용으로 PrivateLink 사용시 
          - DynamoDB 이용을 위한 Backend 프로그램 작성
          - Terraform 코드 작성 및 GitOps 환경 구축

      - layout: left
        title: AWS Micro Service Architecture
        sub_title: Inventory Management
        link: https://xgro.notion.site/AWS-Micro-Service-Architecture-83d38108079f412a84fdff4d8396a08a
        # link_text: Project Website
        additional_links:
          - title:  xgro/inventory_management
            icon: fab fa-github
            url: github.com/xgro/inventory_management
        quote: >
          클라이언트 요구사항에 따라 자동 재고 확보 시스템을 Micro Service Architecture로 구성
        description: | # this will include new lines to allow paragraphs
          - <mark>Serverless framework</mark>를 이용하여 Lambda 배포
          - SQS를 이용하여 서비스간 <mark>느슨한 결합</mark> 구성
          - Dead Letter Queue를 이용하여 메시지 전달 실패시 리드라이브를 통해 시스템 안정성 확보 
          - 서비스 외부의 Callback 메시지를 수신하여 재고 관리
          - k6 이용하여 성능 테스트
          - Terraform 코드 작성하여 IaC 환경 구축 

      - layout: left
        title: AWS Continuous Deploy 
        sub_title: Amazon Elastic Container Service
        link: https://xgro.notion.site/AWS-Continuous-Deploy-093baf2ad9c847d4bbb7aaf3bf4440a1
        # link_text: Project Website
        additional_links:
          - title:  xgro/continuous_deploy
            icon: fab fa-github
            url: github.com/xgro/continuous_deploy
        quote: >
          클라이언트 요구사항에 따라 어플리케이션을 AWS 컨테이너 서비스로 이관하고 CI/CD 파이프라인 구축
        description: | # this will include new lines to allow paragraphs
          - <mark>AWS Codebuild</mark>로 React artifact to S3 CI/CD 파이프라인 구축
          - <mark>Github Action</mark>로 Fastify artifact to ECS CI/CD 파이프라인 구축
          - AWS ECS 서비스를 이용하여 어플리케이션 <mark>컨테이너 환경</mark> 배포
          - Cloudfront 및 ALB 사용하여 https 리다이렉션 기능
          - mongoDB Backend 코드 작성
          - Terraform 작성

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 코드스테이츠
        sub_title: DevOps Bootcamp 02기
        caption: 2022.03 - 2022.08
        quote: >
          DevOps 엔지니어에게 필요한 기본 개념 및 배포 환경 구성 교육
        description: | # this will include new lines to allow paragraphs
          - 자바스크립트의 기본 문법 이해
          - 리눅스 운영체제 기초
          - 웹서비스 및 네트워크 개발 기초
          - AWS 서비스를 이용하여 인프라 구축
          - 컨테이너 환경 어플리케이션 배포
          - 지속적 통합/배포
          - MSA 구성 및 배포
          - IaC를 이용하여 인프라를 코드로 구성
          - 컨테이너 오케스트레이션
          - 모니터링 시스템
          - 성능 테스트

          
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
        quote: >
          현재 업무에 사용중 또는 사용가능한 기술들입니다.
      
      - layout: left
        # 제목
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - Docker, Kubernetes
          - Terraform
          - Prometheus, Grafana
          - k6
          - Nginx, Apache
          
      - layout: left
        # 제목
        title: AWS
        description: | # this will include new lines to allow paragraphs
          - EC2, Lambda
          - ECS, ECR
          - Cloudformation
          - S3
          - SNS, SQS
          - VPC, Route53, Cloudfront, API_Gateway
          - CodeCommit, CodeBuild, CodeDeploy, CodePipeline

      - layout: left
        # 제목
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Node.js, express, fastify

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      이전의 이재찬이 궁금하시다면 아래 링크를 참고 부탁드립니다.
      - [Resume](https://www.jobkorea.co.kr/User/Resume/View?rNo=9681034)
      - [Portfolio](https://file2.jobkorea.co.kr/Net/Mng/UserDown/ResumeAttach?idx=6936996)



# Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
