# Site
repository: xgro/xgro.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이재찬
title: DevOps 엔지니어
email: dlwocks13@gmail.com
website: https://velog.io/@xgro
website_title: Blog

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: xgro
linkedin_username: xgro

# 프로필 작성
# About Section
# about_title: About Me
about_profile_image: images/profile1.jpg
about_content: | # this will include new lines to allow paragraphs
  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# 콘텐츠 작성
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 온프레미스 모놀리틱 서버 - AWS 클라우드 마이그레이션 
        link: https://xgro.notion.site/04-2e4369d70b3d49efb8d75c8900c62f8e
        # link_text: Project Website
        additional_links:
          - title:  xgro/Cloud_Migration
            icon: fab fa-github
            url: github.com/xgro/Cloud_Migration
        quote: >
          클라이언트 요구사항에 따라 온프레미스 환경에서 설치 및 운영되고 있는 사내 정보 시스템을 AWS 클라우드로 이관
        description: | # this will include new lines to allow paragraphs
          ## **What I Did_**
          
          - JWT 토큰 기반의 인증 시스템 Lambda Authorizer 분리
          - Private 환경으로 프로젝트 구성
          - Cloudmap 사용으로 Service Discovery 구현
          - DynamoDB 이용을 위한 Backend 프로그램 작성
          - Terraform 코드 작성 및 GitOps 환경 구축
          
          ## **Result_**
          - VPC 엔드포인트 이용하여 서비스 구축시 285GB 기점으로 비용 절감
          - 모든 서비스를 Private 환경에서 구축
          - 유저 인증을 API_Gateway에서 권한부여자로 처리함으로서 서버 속도 개선
          
          ## **Stack_**
          - API_Gateway, Lambda, Cloudmap, EC2, ECS, ECR, PrivateLink, Terraform, DynamoDB, ELB

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 코드스테이츠
        caption: 2022.03 - 2022.08
        sub_title: DevOps Bootcamp 02기
        quote: >
          DevOps 엔지니어에게 필요한 기본 개념 및 배포 환경 구성 교육
        description: | # this will include new lines to allow paragraphs
          ## **DevOps**
          - AWS 서비스를 이용하여 인프라 구축
          - AWS Code를 이용하여 CI/CD 파이프라인 구축
          - 서버리스 서비스를 이용하여 인프라 구축
          - Private 환경 어플리케이션 구축
          - 어플리케이션 컨테이너화
          - 컨테이너 환경을 ECS를 이용하여 서비스 구축
          - IaC를 이용하여 인프라를 코드로 구성
          - Backend 구성으로 원격 협업 가능 환경 구축
          - helm 이용한 prometheus-grafana 모니터링 구축
          - 자바스크립트의 기본 문법 이해
          
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
        quote: >
          현재 업무에 사용중 또는 사용가능한 기술들입니다.
      
      - layout: left
        # 제목
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - Docker, Kubernetes
          - Terraform
          - Prometheus, Grafana
          - k6
          - Nginx, Apache
          
      - layout: left
        # 제목
        title: AWS
        description: | # this will include new lines to allow paragraphs
          - EC2, Lambda
          - ECS, ECR
          - Cloudformation
          - S3
          - SNS, SQS
          - VPC, Route53, Cloudfront, API_Gateway
          - Code[Commit, Build, Deploy, Pipeline]

      - layout: left
        # 제목
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Node.js, express, fastify

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)


# Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
