# Site
repository: xgro/xgro.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이재찬
title: DevOps 엔지니어
email: dlwocks13@gmail.com
website: https://velog.io/@xgro
website_title: Blog

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  xgro
linkedin_username: xgro

# 프로필 작성
# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>


# 콘텐츠 작성
content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        # 제목
        title: DevOps
        # 
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        # 캡션
        # caption: November 2017 - Present
        # 
        quote: >
          this is quote sesion
        description: | # this will include new lines to allow paragraphs
          - this is description 1 sesion
          - this is description 2 sesion
          - this is description 3 sesion
          - this is description 4 sesion 
          
      - layout: left
        # 제목
        title: AWS
        # 
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        # 캡션
        # caption: November 2017 - Present
        # 
        quote: >
          this is quote sesion
        description: | # this will include new lines to allow paragraphs
          - 
          - 
          -
          -  

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          this is quote sesion
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 코드스테이츠 DevOps Bootcamp
        caption: 2022.03 - 2022.08
        sub_title: DevOps Bootcamp
        quote: >
          this is quote sesion
        description: | # this will include new lines to allow paragraphs
          - this is description sesion

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
